import datetime
import os
from typing import Dict, Any, List
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, KeepTogether
from reportlab.pdfgen import canvas

# Palette Definition
COLOR_PRIMARY = colors.HexColor("#1A365D")    # Deep Navy
COLOR_SECONDARY = colors.HexColor("#0D9488")  # Teal
COLOR_DARK = colors.HexColor("#1E293B")       # Slate Gray (Text)
COLOR_LIGHT = colors.HexColor("#F8FAFC")      # Light Slate (Bg)
COLOR_BORDER = colors.HexColor("#E2E8F0")     # Light gray border
COLOR_ACCENT = colors.HexColor("#D97706")     # Gold/Amber

class NumberedCanvas(canvas.Canvas):
    """
    Custom canvas to perform two-pass page numbering
    so we can show 'Page X of Y' in the footer.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_elements(num_pages)
            super().showPage()
        super().save()

    def draw_page_elements(self, page_count):
        self.saveState()
        
        # 1. Header Band
        self.setFillColor(COLOR_PRIMARY)
        self.rect(54, letter[1] - 40, letter[0] - 108, 3, fill=True, stroke=False)
        
        self.setFont("Helvetica-Bold", 8)
        self.drawString(54, letter[1] - 32, "AI BANKING ASSISTANT")
        self.setFont("Helvetica", 8)
        self.setFillColor(COLOR_DARK)
        self.drawRightString(letter[0] - 54, letter[1] - 32, "DEPOSIT ANALYTICS REPORT")
        
        # 2. Footer Band
        self.setStrokeColor(COLOR_BORDER)
        self.setLineWidth(0.5)
        self.line(54, 50, letter[0] - 54, 50)
        
        self.setFont("Helvetica-Oblique", 8)
        self.drawString(54, 38, "Generated by AI Banking Assistant")
        self.setFont("Helvetica", 8)
        self.drawRightString(letter[0] - 54, 38, f"Page {self._pageNumber} of {page_count}")
        
        self.restoreState()

def format_currency(val: float) -> str:
    """Formats float value as USD/Currency format."""
    return f"${val:,.2f}"

def generate_pdf_report(
    output_path: str,
    original_question: str,
    summary_text: str,
    statistics: Dict[str, Any],
    branch_data: List[Dict[str, Any]]
):
    """
    Builds a professional PDF document using ReportLab.
    """
    # Create the folder if it doesn't exist
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    # 1. Page Template Setup
    # 0.75 margin is 54 points
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=72,
        bottomMargin=72
    )

    styles = getSampleStyleSheet()
    
    # Define custom styles
    title_style = ParagraphStyle(
        name="DocTitle",
        fontName="Helvetica-Bold",
        fontSize=24,
        leading=28,
        textColor=COLOR_PRIMARY,
        spaceAfter=15
    )
    
    h2_style = ParagraphStyle(
        name="SectionHeader",
        fontName="Helvetica-Bold",
        fontSize=14,
        leading=18,
        textColor=COLOR_PRIMARY,
        spaceBefore=15,
        spaceAfter=8,
        keepWithNext=True
    )
    
    meta_label_style = ParagraphStyle(
        name="MetaLabel",
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=11,
        textColor=COLOR_SECONDARY
    )
    
    meta_val_style = ParagraphStyle(
        name="MetaValue",
        fontName="Helvetica",
        fontSize=9,
        leading=11,
        textColor=COLOR_DARK
    )
    
    body_style = ParagraphStyle(
        name="ReportBody",
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=COLOR_DARK,
        spaceAfter=10
    )
    
    q_style = ParagraphStyle(
        name="QuestionText",
        fontName="Helvetica-Oblique",
        fontSize=10,
        leading=14,
        textColor=COLOR_DARK,
        spaceAfter=10
    )
    
    metric_num_style = ParagraphStyle(
        name="MetricNum",
        fontName="Helvetica-Bold",
        fontSize=14,
        leading=16,
        textColor=COLOR_PRIMARY,
        alignment=1 # Center
    )
    
    metric_lbl_style = ParagraphStyle(
        name="MetricLabel",
        fontName="Helvetica",
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#64748B"),
        alignment=1 # Center
    )

    table_header_style = ParagraphStyle(
        name="TableHeader",
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=11,
        textColor=colors.white
    )
    
    table_cell_style = ParagraphStyle(
        name="TableCell",
        fontName="Helvetica",
        fontSize=9,
        leading=12,
        textColor=COLOR_DARK
    )
    
    table_cell_bold_style = ParagraphStyle(
        name="TableCellBold",
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=12,
        textColor=COLOR_DARK
    )

    story = []

    # 1. Document Title & Subtitle
    story.append(Paragraph("Deposit Analytics & Insights", title_style))
    
    # 2. Metadata Block (Side-by-side Key-Value)
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    meta_data = [
        [
            Paragraph("Generated At:", meta_label_style),
            Paragraph(now, meta_val_style),
            Paragraph("Report Scope:", meta_label_style),
            Paragraph("Fixed & Recurring Deposits", meta_val_style)
        ]
    ]
    meta_table = Table(meta_data, colWidths=[90, 160, 90, 160])
    meta_table.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ('TOPPADDING', (0,0), (-1,-1), 0),
        ('LEFTPADDING', (0,0), (-1,-1), 0),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 15))

    # 3. Original Question
    story.append(Paragraph("Original Request:", h2_style))
    story.append(Paragraph(f'"{original_question}"', q_style))
    story.append(Spacer(1, 8))

    # 4. Executive Summary
    story.append(Paragraph("Executive Summary", h2_style))
    story.append(Paragraph(summary_text, body_style))
    story.append(Spacer(1, 10))

    # 5. Key Statistics (Grid block)
    story.append(Paragraph("Key Statistics", h2_style))
    
    # Extract stats or use safe fallbacks
    total_fd_count = statistics.get("fd_count", 0)
    total_fd_vol = statistics.get("fd_total_volume", 0.0)
    total_rd_count = statistics.get("rd_count", 0)
    total_rd_vol = statistics.get("rd_total_monthly", 0.0)
    
    stat_data = [
        [
            Paragraph("Fixed Deposits Booked", metric_lbl_style),
            Paragraph("Fixed Deposit Volume", metric_lbl_style),
            Paragraph("Recurring Deposits Booked", metric_lbl_style),
            Paragraph("Recurring Monthly Volume", metric_lbl_style)
        ],
        [
            Paragraph(f"{total_fd_count:,}", metric_num_style),
            Paragraph(format_currency(total_fd_vol), metric_num_style),
            Paragraph(f"{total_rd_count:,}", metric_num_style),
            Paragraph(format_currency(total_rd_vol), metric_num_style)
        ]
    ]
    
    # 4 columns, total width = 504 (width of letter 612 - 108 margins)
    stat_table = Table(stat_data, colWidths=[126, 126, 126, 126])
    stat_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), COLOR_LIGHT),
        ('BOX', (0,0), (-1,-1), 1, COLOR_BORDER),
        ('INNERGRID', (0,0), (-1,-1), 0.5, COLOR_BORDER),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('TOPPADDING', (0,0), (-1,0), 10),
        ('BOTTOMPADDING', (0,0), (-1,0), 2),
        ('TOPPADDING', (0,1), (-1,1), 2),
        ('BOTTOMPADDING', (0,1), (-1,1), 10),
    ]))
    story.append(stat_table)
    story.append(Spacer(1, 15))

    # 6. Branch-wise Breakdown Table
    story.append(Paragraph("Branch-wise Deposit Distribution", h2_style))
    
    # Header row
    table_data = [[
        Paragraph("Branch", table_header_style),
        Paragraph("FD Bookings", table_header_style),
        Paragraph("FD Total Volume", table_header_style),
        Paragraph("RD Bookings", table_header_style),
        Paragraph("RD Monthly Volume", table_header_style)
    ]]
    
    # Populate rows
    total_fd_cnt_sum = 0
    total_fd_vol_sum = 0.0
    total_rd_cnt_sum = 0
    total_rd_vol_sum = 0.0
    
    for row in branch_data:
        branch_name = row.get("branch", "N/A")
        fd_cnt = row.get("fd_count", 0)
        fd_vol = row.get("fd_total", 0.0)
        rd_cnt = row.get("rd_count", 0)
        rd_vol = row.get("rd_total", 0.0)
        
        total_fd_cnt_sum += fd_cnt
        total_fd_vol_sum += fd_vol
        total_rd_cnt_sum += rd_cnt
        total_rd_vol_sum += rd_vol
        
        table_data.append([
            Paragraph(branch_name, table_cell_style),
            Paragraph(f"{fd_cnt:,}", table_cell_style),
            Paragraph(format_currency(fd_vol), table_cell_style),
            Paragraph(f"{rd_cnt:,}", table_cell_style),
            Paragraph(format_currency(rd_vol), table_cell_style)
        ])
        
    # Append Total row
    table_data.append([
        Paragraph("Total", table_cell_bold_style),
        Paragraph(f"{total_fd_cnt_sum:,}", table_cell_bold_style),
        Paragraph(format_currency(total_fd_vol_sum), table_cell_bold_style),
        Paragraph(f"{total_rd_cnt_sum:,}", table_cell_bold_style),
        Paragraph(format_currency(total_rd_vol_sum), table_cell_bold_style)
    ])
    
    # Total printable width is 504.
    # colWidths: Branch (144), FD Count (80), FD Vol (100), RD Count (80), RD Vol (100) = 504
    col_widths = [144, 80, 100, 80, 100]
    
    branch_table = Table(table_data, colWidths=col_widths, repeatRows=1)
    
    # Style branch table
    t_style = TableStyle([
        ('BACKGROUND', (0,0), (-1,0), COLOR_SECONDARY),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('LINEBELOW', (0,-1), (-1,-1), 1.5, COLOR_PRIMARY), # Bold total row separator
        ('BACKGROUND', (0,-1), (-1,-1), COLOR_LIGHT),
        ('INNERGRID', (0,0), (-1,-1), 0.5, COLOR_BORDER),
        ('BOX', (0,0), (-1,-1), 1, COLOR_SECONDARY),
    ])
    
    # Add alternating row colors for data rows (skip header and total)
    for idx in range(1, len(table_data) - 1):
        if idx % 2 == 0:
            t_style.add('BACKGROUND', (0, idx), (-1, idx), COLOR_LIGHT)
            
    branch_table.setStyle(t_style)
    story.append(KeepTogether([branch_table]))

    # Build PDF
    doc.build(story, canvasmaker=NumberedCanvas)
